import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    learnSidebar: [{ type: "autogenerated", dirName: "docs" }],
    apiSidebar: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
